Repository Anurag-Shraddha-Nimish-Heramba/Final_year_project, pull requests merged in 2022-10, with the labels that each got.

#3 issues-tag table added
  app/Models/Issue.php
  app/Models/Tag.php
  database/migrations/2022_10_02_143232_create_issues_table.php
  database/migrations/2022_10_04_153134_create_issues_tags_table.php
Labels: HACKTOBERFEST-ACCEPTED

#4 Models updated
  app/Models/Comment.php
  app/Models/Issue.php
  app/Models/Status.php
  app/Models/Tag.php
  app/Models/User.php
  database/migrations/2022_10_02_14343_create_comments_table.php
Labels: HACKTOBERFEST-ACCEPTED

#6 Seeding done
  database/factories/CommentFactory.php
  database/factories/IssueFactory.php
  database/factories/IssueTagFactory.php
  database/factories/TagFactory.php
  database/migrations/2022_10_02_14343_create_comments_table.php
  database/seeders/CommentSeeder.php
  database/seeders/IssueSeeder.php
  database/seeders/StatusSeeder.php
  database/seeders/TagSeeder.php
Labels: HACKTOBERFEST-ACCEPTED

#7 Basic Api added
  app/Http/Controllers/LoginController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/LoginRequest.php
  app/Http/Resources/UserResource.php
  database/seeders/DatabaseSeeder.php
  routes/api.php
Labels: HACKTOBERFEST-ACCEPTED

#8 Update and Sign Up User
  app/Http/Controllers/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  database/migrations/2022_10_02_143232_create_issues_table.php
  routes/api.php
Labels: HACKTOBERFEST-ACCEPTED

#9 Tag API; Issue incomplete
  app/Http/Controllers/IssueController.php
  app/Http/Controllers/TagController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/IssueRequest.php
  app/Http/Requests/TagRequest.php
  app/Http/Resources/IssueResource.php
  app/Http/Resources/TagResource.php
  routes/api.php
Labels: HACKTOBERFEST-ACCEPTED

#10 tree structure for comments
  app/Http/Controllers/CommentController.php
  app/Http/Controllers/IssueController.php
  app/Http/Controllers/TagController.php
  app/Http/Controllers/UserController.php
  app/Http/Requests/CommentRequest.php
  app/Http/Resources/CommentResource.php
  app/Models/Comment.php
  app/Models/Issue.php
  composer.json
  composer.lock
  routes/api.php
Labels: HACKTOBERFEST-ACCEPTED

#11 Comment controller commited
  app/Http/Controllers/CommentController.php
Labels: HACKTOBERFEST-ACCEPTED

#14 #13 Code of Conduct added
  Code_of_Conduct.md
Labels: documentation, good first issue, HACKTOBERFEST-ACCEPTED

#15 #13 Basic Readme updated
  README.md
Labels: documentation, good first issue, HACKTOBERFEST-ACCEPTED

#16 Added contributors section
  README.md
Labels: documentation, good first issue, HACKTOBERFEST-ACCEPTED

#17 #13 Added contribution guidelines
  README.md
Labels: documentation, enhancement, HACKTOBERFEST-ACCEPTED
